export const PROFESSOR_DETAILS_REQUEST = "PROFESSOR_DETAILS_REQUEST";
export const PROFESSOR_DETAILS_SUCCESS = "PROFESSOR_DETAILS_SUCCESS";
export const PROFESSOR_DETAILS_FAIL = "PROFESSOR_DETAILS_FAIL";

export const SET_PROFESSOR_SPECIALISATION = "SET_PROFESSOR_SPECIALISATION";
