export const PROFESSOR_DETAILS_REQUEST = "PROFESSOR_DETAILS_REQUEST";
export const PROFESSOR_DETAILS_SUCCESS = "PROFESSOR_DETAILS_SUCCESS";
export const PROFESSOR_DETAILS_FAIL = "PROFESSOR_DETAILS_FAIL";

export const PROFESSOR_DETAIL_REQUEST = "PROFESSOR_DETAIL_REQUEST";
export const PROFESSOR_DETAIL_SUCCESS = "PROFESSOR_DETAIL_SUCCESS";
export const PROFESSOR_DETAIL_FAIL = "PROFESSOR_DETAIL_FAIL";

export const SET_PROFESSOR_SPECIALISATION = "SET_PROFESSOR_SPECIALISATION";
