import os

os.system('python ./approach_1/aerospace.py')
os.system('python ./approach_1/applied_mechanics.py')
os.system('python ./approach_1/biotech.py')
os.system('python ./approach_1/chem_eng.py')
os.system('python ./approach_1/chem.py')
os.system('python ./approach_1/civil.py')
os.system('python ./approach_1/cse.py')
os.system('python ./approach_1/elec.py')
os.system('python ./approach_1/engdesign.py')
os.system('python ./approach_1/humanities.py')
os.system('python ./approach_1/management.py')
os.system('python ./approach_1/material.py')
os.system('python ./approach_1/mathematics.py')
os.system('python ./approach_1/ocean.py')
os.system('python ./approach_1/physics.py')